### ISSUE TITLE
Change direction to delete the notebook

### ISSUE THREAD

**Issue by LenaAn** [zehfernandes/wordnote#10]
I created too many empty notebooks, can I delete it?

**Comment by zehfernandes** [comment]
Hey @LenaAn you can swipe to right in the item to delete the notebooks.

**Comment by coybit** [comment]
@zehfernandes  TBH, out of habit, I tried swiping to the left first, since it's more common in iOS, I guess, but nothing happened, and then I tried swiping to the right. Maybe that's not bad to consider changing the deletion gesture to swipe-left. wdyt?

**Comment by zehfernandes** [comment]
@coybit Good suggestion.

**Comment by zehfernandes** [comment]
fixed https://github.com/zehfernandes/wordnote/pull/20
