### ISSUE TITLE
App stuck “Loading language database”

### ISSUE THREAD

**Issue by OriginalEasyTarget** [zehfernandes/wordnote#15]
App stuck “loading language database” on first launch! Let me know if you need more info. 

![5C9AB2CF-3CFC-4F06-A1FB-64C6EB360D8A](https://user-images.githubusercontent.com/45820974/182441255-a7350ff2-d555-4811-b9d8-e784f584bf7e.png)

**Comment by zehfernandes** [comment]
Opened a issue to investigate it https://github.com/expo/expo/issues/18479

**Comment by zehfernandes** [comment]
fixed https://github.com/zehfernandes/wordnote/pull/20
