### ISSUE TITLE
Plans to package for desktop, too?

### ISSUE THREAD

**Issue by J-HS-L** [zehfernandes/wordnote#6]
This is a "Web App", yeah? If so...
Should be **relatively** easy to package for Win/macOS/Linux/BSD etc.
Given this, any plans to do so?

Thank-you.

**Comment by nvdsalehi** [comment]
You can install it on mac m1 but it is not resizable.
![Screen Shot 2022-08-01 at 10 16 45 AM](https://user-images.githubusercontent.com/25584443/182080414-3ed0e206-e64d-4ba4-8a7f-acf3562d8d80.png)
<img width="455" alt="Screen Shot 2022-08-01 at 10 17 30 AM" src="https://user-images.githubusercontent.com/25584443/182080538-c4bfd379-82a1-43fa-b47e-17d4a6f5fd54.png">

**Comment by hirako2000** [comment]
Why would you that, sorry but that's not a great idea. Web browsers run on all these OS. If there is no other issue.Maybe it's an okay but even then, what is better is this:

Host it on webserver. The app itself.It's a webapp. Serve it as a webapp. It's an app that follows a principle, so it's ok to then be offline. And when online all users will need to do and it will update the app in a blink. 

Installing a packaging a package on any OS, on any OS is pain. A pain for the user. 
It's also a pain for maintainers. To package it. Even with electron. And electron? It will take 150MB at least per app. 

So look, even if you get in there and spend days to change the code to make it work with Electron, it's better to let the browser load the app and render it perfectly in a tab. That tab will take minimal memory. It's less dev work, less maintenance, and it's better UX in the end. 

Please don't package this app. Until the day there is zero issues and we get so bored and can't find any better issue on any of top 10 trending other github repo. 

This repo will trend. But not if we close this issue. Then someone came come and fix it. Ok. Let's do that 😁

**Comment by hirako2000** [comment]
> You can install it on mac m1 but it is not resizable. !)

Browsers resize it fine. All of them pretty much.I'm sure on the browser it resizes properly.

**Comment by nvdsalehi** [comment]
> Browsers resize it fine. All of them pretty much.I'm sure on the browser it resizes properly.

I've used browsers before :D but the whole point of this application is to have it offline.

**Comment by hirako2000** [comment]
I'm sure you did. But unless the README content is misleading, it will work offline. In the browser.

The browser works offline. Not necessarily offline.It can do online too.

I understand why we don't understand web3. I think it's complicated and nobody explains it.

Let's explain web2. Or even web1 it's the same.

Now the browser supports protocols.It always supported protocols. But now those protocols are more standard. One of them is html5. It's the most used.If you don't use html5 then you are learning html4 and you are time travelling.

I think this app, works offline, on the browser, and uses html5 for that. Html5 has support for many things. One is: easy to make the app works offline, for the user AND for the developer.

I'm not sure how that works but I know it works. 😁

**Comment by hirako2000** [comment]
If it doesn't work. I will fix html5. Because packaging would maybe take longer and for what. Let's fix html5 if it's not broken.

I think it's a bit broken, html5, but offline and online works. Almost all browsers support it.

**Comment by hirako2000** [comment]
@nvdsalehi can you try to go offline and see if this app works in the browser? First you need to stay online just once to get the app assets. After that it should work offline. I will test too.

**Comment by zehfernandes** [comment]
Hey @J-HS-L, That's a great idea. I will see if it's worth exporting the react-native to the web or creating a new version running with electron or neutrino.
