### ISSUE TITLE
Built-in iOS Dictionary

### ISSUE THREAD

**Issue by benjibee** [zehfernandes/wordnote#9]
In lieu of a discussions tab, this is an issue, hope it's not distracting.

I've used the Notes app as my dictionary since iOS 8, and it's by far the best I've found. I type out a word, highlight it, and then tap "Look up" from the contextual menu. I have multiple languages on my phone, and iOS provides a dictionary for each one of them.

Your app looks like exactly what I've done for years, just much nicer. Any chance you've looked into using the built-in dictionary and something along the lines of `UITextChecker` or `UIReferenceLibraryViewController.dictionaryHasDefinition()` to get or show a definition? I have no idea if it's permitted, or possible, just wanted to put this out there for discussion.

**Comment by zehfernandes** [comment]
That's a good suggestion, @benjibee.

But I don't know if it is permitted. Let's see if someone from the community knows.

**Comment by zehfernandes** [comment]
Looks like it's not permitted

> App Store guidelines disallow using the built-in system dictionary to create a dictionary app 

https://daringfireball.net/linked/2018/06/19/kotoba

**Comment by benjibee** [comment]
Thanks for this, @zehfernandes at least I have a concrete answer! I might give that app a try, too, as the developer basically described my issue here as the reason for building it.
